### ISSUE TITLE
Add PWM dtbs

### ISSUE THREAD

**Issue by craig-mulligan** [resin-os/resin-beaglebone#127]
BB-PWM0-00A0.dts
BB-PWM1-00A0.dts
BB-PWM2-00A0.dts

Connects to [user request](https://app.frontapp.com/open/cnv_ahqwch).

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3l15)

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-beaglebone/pull/128

**Comment by floion** [comment]
Fix merged. The requested overlays will be available in the next beaglebone release.
Closing this item
