### ISSUE TITLE
Support for Beaglebone Black wireless?

### ISSUE THREAD

**Issue by FRVisser** [resin-os/resin-beaglebone#137]
Hi!

Any change there will be support for the Beaglebone Black wireless? 

Thanks,
Fokko

**Comment by agherzan** [comment]
Hi @FRVisser we don't have this as a priority for now. This is due to the fact that we have many other boards in progress right now. I would encourage you to try to workout patches if this is something your use-case depends on and we will try to integrate them in the next releases.

**Comment by FRVisser** [comment]
Hi @agherzan I did try to patch. It seems to me (but I know nothing about the other Resin components) the only thing needed is adding the board layout to boot (which I did) and edit the uENv.txt to select it. It boot's fine and connect's to the internet over wifi and shows up, but doesn't connect, in the Dashboard. (probably because it is a Beaglebone Black application). I have it on staging right now, and If you like I can leave it running for you.

**Comment by agherzan** [comment]
Thanks @FRVisser for the additional information. @floion please take a look at this when you have a chance.

**Comment by floion** [comment]
@shaunmulligan shall we add this board to our list too? As in, shall we get it in-house and look at it?

**Comment by shaunmulligan** [comment]
@floion yeah sounds like a good idea. I expect it to just work, but lets order some

**Comment by floion** [comment]
@FRVisser can you point us to the exact hw revision you are using?

**Comment by FRVisser** [comment]
Hi @floion, on the silkscreen Rev A5 is printed. I now see, the device online in the Dashboard btw and I can see now the capemgr isn't running. I'll send you the device link in a personal message.

**Comment by floion** [comment]
thanks @FRVisser 
@shaunmulligan so shall we order the exact same revision?

**Comment by shaunmulligan** [comment]
@floion , yeah sounds like a good idea

**Comment by floion** [comment]
@FRVisser can you give an update? Last time we talked this started working. did you reflash to check again?

**Comment by FRVisser** [comment]
@floion ai, it got on my todo list 😔. Give me an hour or 2, then it will be on my done list 👍

**Comment by FRVisser** [comment]
So, I reflashed it and it connected to the dashboard immediately. I even didn't edit the `uENv.txt` file and only added the `am335x-boneblack-wireless.dtb` to `resin-flashA/boot/` and after it was flashed to the `/resin-rootA/balena/.../_data/` folder.

Capemgr is missing, but it could be because of the `dtb` file I used. Just pulled it of the internet form Debian I believe. Link:[am335x-boneblack-wireless.dtb](http://ftp.debian.org/debian/dists/sid/main/installer-armhf/current/images/device-tree/am335x-boneblack-wireless.dtb)

**Comment by floion** [comment]
Thanks. Why did you copy it to the data folder after flashing? that should not be needed IMO

**Comment by FRVisser** [comment]
The `am335x-boneblack-wireless.dtb` doesn't copy over. Only the `uEnv.txt` does.

**Comment by FRVisser** [comment]
Is it possible to just add `/boot/am335x-boneblack-wireless.dtb` to the image file?

**Comment by floion** [comment]
Yeah, that's what I plan to do when I have some time to look at this. Had other things in the queue and hope to get this done this week sometime.

**Comment by floion** [comment]
Hi, on what OS version were you able to have the device online in the dashboard?

**Comment by floion** [comment]
Also, were you connecting to a hidden network?

**Comment by floion** [comment]
Should be fixed by https://github.com/resin-os/resin-beaglebone/pull/142

**Comment by floion** [comment]
2.12.5+rev1 with the above PR merged, has been deployed to our staging environment. Can you try it on your side and let us know if it works for you?
Thanks

**Comment by FRVisser** [comment]
@floion I currently have it on Resin OS 2.9.6+rev1 (dev). It showed up in the dashboard without problems. I didn't test a hidden network.

I'll test 2.12.5+rev1 today. Saw it passing by in the release notes.
Thanks

**Comment by floion** [comment]
Hi @FRVisser did you have a chance to check this? Thanks

**Comment by FRVisser** [comment]
@floion Yes it works flawlessly, including the cape-manager. 
Thanks!

**Comment by floion** [comment]
Good. Closing this item
