### ISSUE TITLE
remove the `remove_to_reprovision` file from boot

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resin-beaglebone#15]
This file is legacy and should probably be removed I think.

**Comment by agherzan** [comment]
This is indeed an issue in meta-resin. Moving it accordingly.

**Comment by agherzan** [comment]
Issue moved to [resin-os/meta-resin #80](https://github.com/resin-os/meta-resin/issues/80) via [**ZenHub.io**](https://www.zenhub.io/)
