### ISSUE TITLE
Boot/reboot/shutdown splash screen

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-beaglebone#3]
# Steps to reproduce issue 
Connect to the HDMI connected to a monitor
Boot the device

# Expected result 
Resin logo splash screen should be visible

# Actual result 
Resin logo not displayed at boot-up. (to be double checked with a different HDMI display)

At reboot/shutdown the logo is displayed correctly

# Other information 
Reported by: Florin Sarbu 

Test configuration: Beaglebone 

Test case number: TC07 

Test run: [https://resinio.testlodge.com/projects/16238/runs/196239?tab=2&run_section_id=176148&executed_case_id=9459429#executed_case_9459429](https://resinio.testlodge.com/projects/16238/runs/196239?tab=2&run_section_id=176148&executed_case_id=9459429#executed_case_9459429)

**Comment by floion** [comment]
Issue no longer reproducible on kernel 4.4.21+
Closing
