### ISSUE TITLE
Install missing latest BT firmware for BBGW

### ISSUE THREAD

**Issue by imrehg** [resin-os/resin-beaglebone#33]
The latest BT firmware for BeagleBone Green Wifi seems to be using `TIInit_11.8.32.bts`, but we don't ship that. Since user applications can't very well pull in firmware (because of shadowing `/lib/firmware`, we should definitely install it. Also, it's almost 2 years old now. :)

Looks like the file has a number of different versions, the one installed from this repo appears to be working (done some device scanning as test, but that's all): https://github.com/rcn-ee/repos

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lrx)

**Comment by agherzan** [comment]
This issue was moved to resin-os/resinos#79
