### ISSUE TITLE
Automatic detection of SD card and boot from there if it's a resin image

### ISSUE THREAD

**Issue by imrehg** [resin-os/resin-beaglebone#40]
If an SD card is inserted that looks like an OS image as it's set up in resin, boot from there, without requiring the pressing of the USER button on start. This would enable interactionless image install on the BeagleBone boards, and also relevant for running from the SD card directly (https://github.com/resin-io/hq/issues/369). It should be able to do the following with careful choices of the uboot parameters.

One possible issue is supporting boards with factory-default setup/uboot, and different locations where the uboot is possibly stored.

For reference, the a beaglebone image builder project with relevant scripts is here: https://github.com/RobertCNelson/omap-image-builder

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_nc5)

**Comment by agherzan** [comment]
This issue was moved to resin-os/resinos#81
